spring.application.name=electrical-services-inventory-analytics

#database configurations
spring.datasource.url=jdbc:mysql://localhost:3306/mathapati_electricals
spring.datasource.username=root
spring.datasource.password=Road@1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true